### ISSUE TITLE
Add task to tell weather of your city

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Nitesh-thapliyal/Automation#3]

**Comment by Vyvy-vi** [comment]
I would be interested in this.
I'll add a weather API, but we might need to set a .env for the API keys..

**Comment by Nitesh-thapliyal** [comment]
Ok go for it

**Comment by Vyvy-vi** [comment]
`weather <city-name>` or some other format?

**Comment by Nitesh-thapliyal** [comment]
Do as you like but it should work, try it if it not works I will make changes

**Comment by Vyvy-vi** [comment]
Ok, should it speak the weather, or open a browser tab with the weather info? (browser-tab would be faster in responding)

**Comment by Nitesh-thapliyal** [comment]
speak
